DROP TABLE IF EXISTS `GlyphSlot`; 
CREATE TABLE `GlyphSlot` ( `ID` INT NOT NULL DEFAULT '0',
 `Type` INT NOT NULL DEFAULT '0',
 `Tooltip` INT NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8; 
INSERT INTO `GlyphSlot` VALUES (1,4,0); 
INSERT INTO `GlyphSlot` VALUES (2,2,0); 
INSERT INTO `GlyphSlot` VALUES (3,3,0); 
INSERT INTO `GlyphSlot` VALUES (4,0,0); 
INSERT INTO `GlyphSlot` VALUES (21,0,1); 
INSERT INTO `GlyphSlot` VALUES (22,1,2); 
INSERT INTO `GlyphSlot` VALUES (23,1,3); 
INSERT INTO `GlyphSlot` VALUES (24,0,4); 
INSERT INTO `GlyphSlot` VALUES (25,1,5); 
INSERT INTO `GlyphSlot` VALUES (26,0,6); 
