DROP TABLE IF EXISTS `GtChanceToMeleeCritBase`; 
CREATE TABLE `GtChanceToMeleeCritBase` ( `ID` INT NOT NULL DEFAULT '0',
 `Data` FLOAT NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8; 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (1,0.031891); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (2,0.032685); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (3,-0.01532); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (4,-0.00295); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (5,0.031765); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (6,0.031891); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (7,0.02922); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (8,0.03454); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (9,0.02622); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (10,0.2); 
INSERT INTO `GtChanceToMeleeCritBase` VALUES (11,0.074755); 
