DROP TABLE IF EXISTS `PowerDisplay`; 
CREATE TABLE `PowerDisplay` ( `ID` INT NOT NULL DEFAULT '0',
 `ActualType` INT NOT NULL DEFAULT '0',
 `GlobalstringBaseTag` TEXT NULL,
 `Red` TINYINT UNSIGNED NOT NULL DEFAULT '0',
 `Green` TINYINT UNSIGNED NOT NULL DEFAULT '0',
 `Blue` TINYINT UNSIGNED NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8; 
INSERT INTO `PowerDisplay` VALUES (1,0,"AMMOSLOT",255,128,0); 
INSERT INTO `PowerDisplay` VALUES (41,3,"POWER_TYPE_PYRITE",0,202,255); 
INSERT INTO `PowerDisplay` VALUES (61,3,"POWER_TYPE_STEAM",242,242,242); 
INSERT INTO `PowerDisplay` VALUES (101,3,"POWER_TYPE_HEAT",255,125,0); 
INSERT INTO `PowerDisplay` VALUES (121,3,"POWER_TYPE_OOZE",193,255,0); 
INSERT INTO `PowerDisplay` VALUES (141,3,"POWER_TYPE_BLOOD_POWER",188,0,255); 
INSERT INTO `PowerDisplay` VALUES (142,3,"POWER_TYPE_WRATH",255,176,0); 
