DROP TABLE IF EXISTS `SpellFocusObject`; 
CREATE TABLE `SpellFocusObject` ( `ID` INT NOT NULL DEFAULT '0',
 `Name_Lang_enUS` TEXT NULL,
 `Name_Lang_enGB` TEXT NULL,
 `Name_Lang_koKR` TEXT NULL,
 `Name_Lang_frFR` TEXT NULL,
 `Name_Lang_deDE` TEXT NULL,
 `Name_Lang_enCN` TEXT NULL,
 `Name_Lang_zhCN` TEXT NULL,
 `Name_Lang_enTW` TEXT NULL,
 `Name_Lang_zhTW` TEXT NULL,
 `Name_Lang_esES` TEXT NULL,
 `Name_Lang_esMX` TEXT NULL,
 `Name_Lang_ruRU` TEXT NULL,
 `Name_Lang_ptPT` TEXT NULL,
 `Name_Lang_ptBR` TEXT NULL,
 `Name_Lang_itIT` TEXT NULL,
 `Name_Lang_Unk` TEXT NULL,
 `Name_Lang_Mask` INT UNSIGNED NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8; 
INSERT INTO `SpellFocusObject` VALUES (1,"Anvil","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (2,"Loom","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (3,"Forge","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (4,"Cooking Fire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (5,"Shards of Myzrael","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (6,"Winterhoof Water Well","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (7,"Thunderhorn Water Well","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (8,"Wildmane Water Well","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (9,"Tribal Fire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (10,"Machine Shop","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (11,"Shadowglen Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (12,"Starbreeze Village Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (13,"Pools of Arlithrien Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (14,"Oracle Glade Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (15,"Venture Co. Airport","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (16,"Venture Co. Wagon (Blue)","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (17,"Venture Co. Wagon (Red)","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (18,"NG-5 Explosives (Red)","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (19,"NG-5 Explosives (Blue)","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (20,"Flame of Uzel","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (21,"Ashenvale Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (22,"Seaworn Altar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (23,"Nearby Tubers","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (43,"Undercity Summoning Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (63,"Shaman Shrine","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (83,"Stormwind Summoning Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (103,"Barrens Summoning Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (123,"Mirror Lake Waterfall","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (143,"Talon Den","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (163,"Xavian Waterfall","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (164,"Stone of Outer Binding","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (183,"Mana Rift Disturbance","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (203,"Orgrimmar Summoning Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (223,"Wrathscale Fountain","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (224,"Quilboar Watering Hole","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (225,"Water Purity - Silverpine","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (226,"Spring Well","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (243,"Temple of the Moon Fountain","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (263,"Jintha\\'Alor Altar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (264,"Pirate Ship Bilge","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (283,"Equinex Monolith","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (303,"Witherbark Village","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (304,"Shadra\\'Alor Altar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (323,"Sandsorrow Watch Water Hole","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (343,"Hatetalon Stones","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (363,"Echeyakee\\'s Lair","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (383,"The Dead Tree","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (403,"Makeshift Helipad","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (423,"Circle of Aquementas","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (424,"Sanctum of the Fallen God","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (443,"the First Tide Pool","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (444,"the Second Tide Pool","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (445,"the Third Tide Pool","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (446,"the Fourth Tide Pool","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (463,"Gorishi Hive Hatchery","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (483,"Miblon Snarltooth","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (503,"Gadgetzan Graveyard","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (523,"the ruins of Irontree Woods","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (543,"Black Forge","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (563,"Golakka Crater","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (583,"Tomb of the Seven","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (603,"Flat Un\\'Goro Rock","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (604,"Preserved Threshadon Carcass","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (623,"Black Anvil","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (643,"Gorishi Silithid Crystal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (644,"Corrupted Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (663,"Alchemy Lab","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (683,"Unforged Seal of Ascension","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (703,"Auberdine Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (704,"Blackwood Furbolg North Bonfire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (705,"Cliffspring River Waterfall","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (723,"Fire Plume Ridge Hot Spot","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (743,"Urok\\'s Tribute Pile","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (763,"Andorhal Silo Temporal Rift","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (783,"Stone of Shy-Rotam","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (803,"Sacred Fire of Life","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (804,"Scarlet Crusade Forward Camp","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (805,"Andorhal Tower","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (823,"Scholomance Viewing Room","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (843,"the Jaedenar Corrupt Moon Well","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (863,"Umi\\'s Friend","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (883,"Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (903,"Fire Plume Ridge Lava Lake","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (923,"the crate in the center of the Northridge Lumber Mill","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (943,"Moonkin Stone","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (944,"Darrowshire Town Square","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (963,"Bright Light Beam","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (983,"Mark of Detonation","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1003,"Cliffspring Falls Cave Mouth","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1004,"Dreadmist Peak Pool","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1023,"The Dead Goliaths","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1043,"Shrine of Remulos","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1063,"Foulweald Totem Mound","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1083,"Dire Pool","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1103,"Maraudon Portal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1123,"Horde Globe of Scrying","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1143,"Eastern Crater","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1144,"Western Crater","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1145,"Snowfall Graveyard","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1163,"Alliance Globe of Scrying","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1164,"Dun Baldar Courtyard","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1165,"Frostwolf Keep Courtyard","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1183,"Snowfall Graveyard","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1184,"East Crater","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1185,"West Crater","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1203,"Orange Crystal Pool","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1223,"Onyxia\\'s Flame Breath","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1243,"Kroshius\\' Remains","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1263,"Pedestal of Immol\\'thar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1264,"Circle of Dark Summoning","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1283,"The Great Ossuary","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1284,"Terrordale Haunting Spirit","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1303,"Aerie Peak Town Center","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1323,"Uther\\'s Tomb Statue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1324,"Grom\\'s Monument","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1343,"Pagle\\'s Pointe","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1344,"Altar of Zanza","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1345,"Southshore","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1346,"Bones of Grakkarond","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1347,"Forsaken Stink Bomb","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1348,"Drop-Off Point","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1349,"Swirling Maelstrom","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1350,"High Chief Winterfall\\'s Cave","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1351,"Firework Launcher","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1352,"Cluster Launcher","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1353,"Greater Moonlight","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1354,"Voone\\'s Chamber","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1355,"Alzzin\\'s Chamber","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1356,"The Crimson Throne","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1357,"Ras Frostwhisper\\'s Chamber","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1358,"The Beast\\'s Chamber","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1359,"Haunted Locus","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1360,"Blackrock Depths Arena","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1361,"[PH] Crystal Corpse","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1362,"Icebellow Anvil","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1363,"Eversong Runestone","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1364,"Consecrated Earth","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1365,"Midsummer Bonfire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1366,"Maypole","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1367,"Altar of Aggonar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1368,"Bones of Aggonar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1369,"School of Red Snapper","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1370,"Krun Spinebreaker\\'s Corpse","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1371,"Thalanaar Moonwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1372,"Concealed Control Panel","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1373,"Altar of Naias","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1374,"Discreet Location","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1375,"Rune of Summoning","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1376,"Fel Brazier","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1377,"you to be in Traitor\\'s Cove while the Naga Flag is up.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1378,"Sedai\\'s Corpse","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1379,"Nazzivus Monument","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1380,"Impact Site Crystal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1381,"Altered Bloodmyst Crystal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1382,"Axxarien Crystal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1383,"the southern end of the Master\\'s Terrace","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1384,"Medivh\\'s Telescope","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1385,"Alonsus Chapel Eternal Flame","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1386,"Bloodmyst Waterfall","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1387,"Steam Pump Controls","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1388,"Windyreed Hut","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1389,"Earthen Brand","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1390,"Underground Water Source","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1391,"Boha\\'mu Ruins Stairs","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1392,"Daggerfen Rock","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1393,"Burning Blade pyre in the Burning Blade Ruins.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1394,"Ysiel\\'s Balcony","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1395,"Blazing Warmaul Pyre","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1396,"Veil Shalas Totem","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1397,"Trampled Skeleton","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1398,"Alliance Cannon","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1399,"Horde Blade Thrower","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1400,"Legion Antenna","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1401,"Scorched Grove Runestone","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1402,"Bookcase","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1403,"Weapon Rack","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1404,"Dresser","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1405,"Footlocker","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1406,"Ruined Alliance Siege Tower","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1407,"Uncontrolled Scrap Reaver X6000","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1408,"Kirin\\'Var Rune","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1409,"Archmage Vargoth\\'s Orb","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1410,"Elrendar Falls","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1411,"Dragon Skeleton","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1412,"Ethereal Teleport Pad","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1413,"Arklon Brazier","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1414,"Void Stone","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1415,"Manaforge B\\'naar Pipe","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1416,"Draenei Banner","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1417,"Earthbinder\\'s Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1418,"Salhadaar\\'s Power Conduit","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1419,"Socrethar\\'s Teleporter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1420,"Eco-Dome Sutheron Generator","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1421,"you to be closer to Manaforge Ultris","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1422,"Northmaul Tower","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1423,"Altar of Shadows","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1424,"Shadowmoon Tuber Mound","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1425,"Rokgah Bloodgrip","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1426,"Mana Loom","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1427,"Ancient Draenei Altar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1428,"Ogre Building Entrance","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1429,"Blade\\'s Edge Arakkoa Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1430,"Lashh\\'an Spell Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1431,"Vekh\\'nir Circle of Power","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1432,"you to be at the end of the bridge.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1433,"Torgos\\'s Bane","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1434,"Vekh\\'nir Spell Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1435,"you to be standing next to Gul\\'dan at the Altar of Damnation.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1436,"Legion Hold Teleporter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1437,"Ruuan\\'ok Oracle Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1438,"Legion Communication Device","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1439,"Foreman Razelcraz","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1440,"Portal at Marshlight Lake","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1441,"Blade\\'s Edge - Quest - Bird Spying","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1442,"Malukaz\\'s Candles","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1443,"Bleeding Hollow Forge","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1444,"Marmot Den","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1445,"Gehenna Teleporter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1446,"Force Commander Gorax\\'s Corpse","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1447,"Zeth\\'Gor Tower","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1448,"Unguarded Summoning Site","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1449,"Locked Wyvern Cage","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1450,"Gorgrom\\'s Corpse","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1451,"Death\\'s Door Fel Cannon","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1452,"Writhing Mound Summoning Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1453,"Altar of Goc and that Goc has not been summoned","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1454,"The Raven\\'s Claw","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1455,"Arakkoa Shrine","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1456,"Soulgrinder\\'s Altar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1457,"Shartuul\\'s Transporter Platform","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1458,"Shipwreck Debris","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1459,"Blackhoof Village Windmill","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1460,"Grimtotem Tent","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1461,"Hyal Family Monument","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1462,"Burning Troll Hut","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1463,"Entrance to Onyxia\\'s Lair","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1464,"Swamplight Manor Dock","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1465,"The Wyrmcaller\\'s Platform","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1466,"Shattered Strand Cannon","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1467,"cannon on northern Alliance wall.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1468,"The Thane\\'s Pyre","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1469,"Frozen Waterfall","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1470,"proximity to plaguehound cages at Vengeance Landing.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1471,"Standing at the Booth Counter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1472,"Cauldron of Vrykul Blood.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1473,"Harris\\'s Plague Samples.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1474,"you to be closer to plaguehound cages.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1475,"Broken Tablet","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1476,"Sunken Boat","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1477,"Center of Baleheim","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1478,"Brewfest - Mug Request","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1479,"Walt\\'s Transport Rune","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1480,"Iron Dwarf Transport Rune","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1481,"Ley Lines of Quel\\'Danas","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1482,"Razorthorn Dirt Mound","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1483,"Crystal Ward","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1484,"Legion Teleporter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1485,"Hauthaa\\'s Anvil","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1486,"Vrykul Burial Mound","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1487,"Westrift Seismic Anomaly","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1488,"JSB - Reuse post 2.4.0","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1489,"Nerub\\'ar Sinkhole","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1490,"Snarlfang\\'s Totem","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1491,"En\\'kilah Cauldron","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1492,"you to be at or near the front of a Kvaldir ship.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1493,"you to be standing at the end of Warsong Jetty.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1494,"Imprisoned Beryl Sorcerer","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1495,"Beryl Force Shield","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1496,"Den of Dying Plague Cauldron","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1497,"South Sinkhole","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1498,"you to be at the crossroads, east of Warsong Hold with an Alliance Deserter in tow.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1499,"you to be standing next to Bloodmage Laurith at the Bloodspore Plains.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1500,"Shattered Sun Portal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1501,"Shattered Sun Portal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1502,"Crashed Flying Machine","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1503,"Geyser Fields Steam Vent","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1504,"Nexus Dimensional Rift","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1505,"Farshire Grain","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1506,"Saragosa\\'s Landing","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1507,"proximity to a Scourge sinkhole.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1508,"Northwest Nexus Entrance","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1509,"Drakuru\\'s Brazier","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1510,"East End of Thor Modan Tunnel","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1511,"Tua\\'kea\\'s Fishing Hook","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1512,"Toalu\\'u\\'s Brazier","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1513,"Fizzcrank Practice Parachute Zone","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1514,"Fizzcrank Paratrooper Teleporter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1515,"Ley Line Focus on the Beach","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1516,"Ley Line Focus in the Lothalor Woodlands","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1517,"Ley Line Focus Under the Lake","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1518,"Drakil\\'jin Gongs","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1519,"Marked Coldwind Tree","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1520,"Center of the pit under the Surge Needle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1521,"depths below Vordrassil\\'s remains.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1522,"depths below Vordrassil\\'s Limb.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1523,"depths below Vordrassil\\'s Tears.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1524,"Hansel Bauer","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1525,"Grom\\'thar\\'s Challenging Area","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1526,"Wintergarde Gryphon Station","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1527,"New Hearthglen Lumbermill","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1528,"Vordrassil\\'s Sapling","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1529,"Basecamp","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1530,"Obsidian Dragonshrine Exit Path","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1531,"you to be standing next to Siege Engineer Quarterflash.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1532,"Necromantic Rune","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1533,"you to be standing at one of the entrance points to Wintergarde Mine.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1534,"School of Northern Salmon","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1535,"you to be standing in the center of the ruins at the Forgotten Shore.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1536,"you to be at the front of the Wintergarde Mausoleum.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1537,"Ruuna\\'s Crystal Ball","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1538,"Squire Percy","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1539,"that you be closer to Alystros the Verdant Keeper","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1540,"Frostmourne Altar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1541,"that you be on the sands of the Bronze Dragonshrine","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1542,"Vrykul Hawk Roost","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1543,"Scourged Mummy Fire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1544,"Drakkari Ritual Statue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1545,"Finklestein\\'s Cauldron","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1546,"Mistwhisper Weather Shrine","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1547,"Offering Bowl","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1548,"Drakkari Pedestal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1549,"Fallen Log","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1550,"Ancient Dirt Mound","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1551,"Nerubian Crater","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1552,"Runeforge","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1553,"Landing Pad","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1554,"Scourgewagon","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1555,"Quetz\\'lun\\'s Corpse and that the Prophet of Quetz\\'lun be present and unengaged","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1556,"Altar of Kartak","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1557,"Great Lightning Stone","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1558,"Warlord Zol\\'Maz present and unengaged in combat.","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1559,"Top of the Suntouched Pillar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1560,"Convocation Summoning Circle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1561,"Soaked Fertile Dirt","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1562,"Top of Sholazar Pillar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1563,"Top of the Glimmering Pillar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1564,"Exposed Lifeblood Pillar Crystal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1565,"Uzo Deathcaller","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1566,"Archbishop Landgren\\'s corpse and Lord-Commander Arete not be present","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1567,"School of Tasty Reef Fish","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1568,"Magmawyrm Resurrection Chamber","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1569,"Frostgut\\'s Altar","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1570,"Garm Teleporter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1571,"Thane Ufrang the Mighty present and seated","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1572,"Northern Ice Spike","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1573,"Icy Crater","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1574,"Vanguard Infirmary","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1575,"Snowdrift","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1576,"the Broodmother\\'s Nest","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1577,"K3 Landing","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1578,"Thane Illskar be present and that he and his champions not be engaged in battle","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1579,"Pile of Crusader Skulls","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1580,"Malykriss Furnace","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1581,"Ahn\\'kahet Brazier","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1582,"Sanctum of Reanimation Slab","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1583,"Dalaran Fountain","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1584,"Ymirheim Peak Skulls","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1585,"Mord\\'rethar Plague Cauldron","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1586,"Grimkor\\'s Orb","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1587,"Cultists\\' Cauldron","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1588,"Alumeth\\'s Soulstone","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1589,"you to be near a Lexicon of Power","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1590,"Smoldering Scrap","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1591,"Altar of the Ebon Depths","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1592,"Corpse of the Fallen Worg","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1596,"Unlit Signal Fire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1597,"Drak\\'Mar Offering Ring","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1599,"Tournament Stables","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1601,"Black Knight\\'s Gryphon","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1602,"Stone Block","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1613,"Ghostly Cooking Fire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1618,"Mysterious Snow Mound","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1620,"Mistcaller\\'s Cave","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1621,"Tualiq Monuments","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1622,"the deck of Bor\\'s Fury","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1636,"Forgemaster\\'s Anvil","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1639,"Crown Supply Camp","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1641,"Sunwell","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `SpellFocusObject` VALUES (1650,"Chemical Wagon","","","","","","","","","","","","","","","",16712190); 
