DROP TABLE IF EXISTS `StableSlotPrices`; 
CREATE TABLE `StableSlotPrices` ( `ID` INT NOT NULL DEFAULT '0',
 `Cost` INT NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8; 
INSERT INTO `StableSlotPrices` VALUES (1,500); 
INSERT INTO `StableSlotPrices` VALUES (2,50000); 
INSERT INTO `StableSlotPrices` VALUES (3,500000); 
INSERT INTO `StableSlotPrices` VALUES (4,1500000); 
